[package]
name = "libr2k"
version = "0.1.0"
authors = ["SiIky <siikyatgith@openaliasbox.org>"]
repository = "https://github.com/siiky/libr2k"
readme = "README.md"
license = "Unlicense"

[dependencies]
unicode-jp = "*"
