[package]
name = "r2k"
version = "0.1.0"
authors = ["SiIky <SiIky@users.noreply.github.com>"]
repository = "https://github.com/siiky/r2k"
readme = "README.md"
license = "Unlicense"

[dependencies]
clap = "*"
unicode-jp = "*"
